name: meu_app
description: Um aplicativo Flutter.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.18.0
  firebase_core: ^4.6.0
  cloud_firestore: ^6.2.0
  firebase_auth: ^6.3.0  # <-- adicione isto

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  rename: ^3.0.0

flutter:
  uses-material-design: true
