// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz5u-FdwNhT1xcN1QYjkLMk1I6WNiLcdY',
    appId: '1:823023602721:web:7b61dde594c3b2adb4a760',
    messagingSenderId: '823023602721',
    projectId: 'one-finance-d8165',
    authDomain: 'one-finance-d8165.firebaseapp.com',
    storageBucket: 'one-finance-d8165.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCQy19KhBzx1JGEixOlO7WOAFDdr2RDho',
    appId: '1:823023602721:android:720087c030519ce9b4a760',
    messagingSenderId: '823023602721',
    projectId: 'one-finance-d8165',
    storageBucket: 'one-finance-d8165.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz3YH8_vQNs5CBXakeYIZqp3CUIoO4uZM',
    appId: '1:823023602721:ios:f39091ebb3e37289b4a760',
    messagingSenderId: '823023602721',
    projectId: 'one-finance-d8165',
    storageBucket: 'one-finance-d8165.firebasestorage.app',
    iosBundleId: 'com.example.oneFinance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz3YH8_vQNs5CBXakeYIZqp3CUIoO4uZM',
    appId: '1:823023602721:ios:f39091ebb3e37289b4a760',
    messagingSenderId: '823023602721',
    projectId: 'one-finance-d8165',
    storageBucket: 'one-finance-d8165.firebasestorage.app',
    iosBundleId: 'com.example.oneFinance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDz5u-FdwNhT1xcN1QYjkLMk1I6WNiLcdY',
    appId: '1:823023602721:web:190fc787156a02aeb4a760',
    messagingSenderId: '823023602721',
    projectId: 'one-finance-d8165',
    authDomain: 'one-finance-d8165.firebaseapp.com',
    storageBucket: 'one-finance-d8165.firebasestorage.app',
  );
}
